#ESCREVA UM PROGRAMA QUE LEIA 2 NÚMEROS INTEIROS E COMPARE-OS INFORMANDO:
#(1) O 1º VALOR É MAIOR, (2) O 2º VALOR É MAIOR, (3) NÃO EXISTE VALOR MAIOR, ELES SÃO IGUAIS.
"""
1. Ler número inteiro
2. Comparar qual é o maior e informar
"""