#CRIE UM PROGRAMA QUE LEIA DUAS NOTAS DE UM ALUNO E CALCULE SUA MÉRIA, MOSTRANDO UMA MENSAGEM DE ACORDO COM A MÉDIA ATINGIDA:
#ABAIXO DE 5.0 - REPROVADO
#DE 5.0 À 6.9 - RECUPERAÇÃO
#7.0 OU ACIMA - APROVADO
#(MINHA INVENÇÃO) - SE MÉDIA 9.5 OU ACIMA DIZER QUE ESTÁ DE PARABÉNS PELA DEDICAÇÃO
"""
1. Ler nota1
2. Ler nota2
3. Calcular média
4.1. Se média <5: REPROVADO
4.2. Se média >=5 and <=6.9: RECUPERAÇÃO
4.3. Se média >=7: APROVADO
4.3.1. Se média >=9.5: Parabenizar dedicação
"""