#ESCREVA UM PROGRAMA QUE FAÇA O PC "PENSAR" EM UM NÚMERO INTEIRO ENTRE 0 E 10.
#PEÇA PARA O USUÁRIO DESCOBRIR QUAL FOI, DANDO OPÇÃO DE CHUTAR QUANTAS VEZES PRECISAR.
#O PROGRAMA DEVE INFORMAR SE ACERTOU OU NÃO E QUANTOS PALPITES FORAM NECESSÁRIOS PARA ACERTAR
