#PREENCHER TUPLA COM OS 20 PRIMEIROS DO BRASILEIRÃO, NA ORDEM DE COLOCAÇÃO. MOSTRAR:
#A - APENAS OS 5 PRIMEIROS;
#B - OS ÚLTIMOS 4 COLOCADOS;
#C - TODOS EM ORDEM ALFABÉTICA; E
#D - POSIÇÃO DO CHAPECOENSE;
