#LER VÁRIOS NÚMEROS E COLOCAR NUMA LISTA, QUESTIONANDO SE QUER CONTINUAR. MOSTRAR:
#A - QUANTOS NÚMEROS FORAM DIGITADOS;
#B - A LISTA DE VALORES ORDENADA DE FORMA DECRESCENTE;
#C - SE O VALOR 5 FOI DIGITADO E ESTÁ OU NÃO NA LISTA.

